// Generated by CoffeeScript 1.7.1
(function() {
  var context_read, funcToInject, jsCodeStr, read, start_callback, version;

  version = chrome.app.getDetails().version;

  if (localStorage['lastVersionUsed'] !== version) {
    localStorage['lastVersionUsed'] = version;
    chrome.tabs.create({
      url: chrome.extension.getURL('options.html')
    });
  }

  funcToInject = function() {
    return window.getSelection().toString();
  };

  jsCodeStr = ";(" + funcToInject + ")();";

  start_callback = function(e) {
    var cb, details;
    details = {
      code: jsCodeStr,
      allFrames: true
    };
    cb = function(arr) {
      if (chrome.runtime.lastError) {
        console.log(chrome.runtime.lastError);
        return read(chrome.runtime.lastError.message);
      } else {
        if (arr[0] === "") {
          return chrome.tabs.create({
            url: chrome.extension.getURL('options.html')
          });
        } else {
          return read(arr[0]);
        }
      }
    };
    return chrome.tabs.executeScript(details, cb);
  };

  read = function(text) {
    var cb, opts;
    text = encodeURIComponent(text);
    opts = {
      url: chrome.extension.getURL("main.html?text=" + text),
      width: 960,
      height: 600,
      type: "popup"
    };
    cb = function(wind) {
      if (localStorage['fullscreen'] === "true") {
        return chrome.windows.update(wind.id, {
          state: "fullscreen"
        });
      }
    };
    return chrome.windows.create(opts, cb);
  };

  context_read = function(context) {
    return read(context.selectionText);
  };

  chrome.commands.onCommand.addListener(start_callback);

  chrome.browserAction.onClicked.addListener(start_callback);

  chrome.contextMenus.create({
    "title": "3read",
    "contexts": ["selection"],
    "onclick": context_read
  });

}).call(this);
